#!/bin/bash

echo "Checking for existing mysql container";
if [[ $(sudo docker ps -a | grep mysql) ]]; then
  echo "Removing old mysql container";
  sudo docker rm -f mysql;
fi
PASS="**RANDOM**";
if [ Argv[1] ]; then
  PASS=Argv[1];
fi

sudo docker run -d -p 3306:3306 \
  -v /eol/mysql/lib:/var/lib/mysql \
  -v /eol/mysql/log:/var/log/mysql \
  -e MYSQL_PASS=PASS \
  --name=mysql eolmysql
