#!/bin/bash

echo "Checking for existing mysql container";
if [[ $(sudo docker ps -a | grep mysql) ]]; then
  echo "Removing old mysql container";
  sudo docker rm -f mysql;
fi
sudo docker run -d -p 3306:3306 \
  -v /eol/mysql/lib:/var/lib/mysql \
  -v /eol/mysql/log:/var/log/mysql \
  -e MYSQL_PASS=Argv[1] || "**RANDOM**" \
  --name=mysql eolmysql
